"""
Pydantic Data Models for Multilingual LLM Answer Generation & Reliability (Phase 8 / Groq Production System)

Defines schemas for generation requests, source attributions, grounding status enums,
and full answer responses with measured latency breakdowns and verification metrics.
"""

from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class GroundingStatus(str, Enum):
    """Consistent status flags for retrieval grounding, verification, and provider execution."""
    GROUNDED = "GROUNDED"
    PARTIALLY_GROUNDED = "PARTIALLY_GROUNDED"
    UNGROUNDED = "UNGROUNDED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    NO_CONTEXT = "NO_CONTEXT"
    UNSAFE_QUERY = "UNSAFE_QUERY"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"


class AskRequest(BaseModel):
    """Container for user ask/generation requests."""
    query: str = Field(..., description="Original user query string preserved exactly in English or any supported Indic language")
    top_k: int = Field(default=5, ge=1, le=50, description="Maximum number of context chunks to retrieve")
    score_threshold: float = Field(default=0.0, ge=-1.0, le=1.0, description="Minimum cosine similarity score threshold")
    language_filter: Optional[str] = Field(default=None, description="Optional language filter code (e.g. 'hi', 'mr', 'ta')")
    preferred_answer_language: Optional[str] = Field(default=None, description="Preferred language code for generated answer")


class SourceAttribution(BaseModel):
    """Source chunk attribution metadata returned with answer, strictly validated against FAISS or Web store records."""
    chunk_id: str = Field(..., description="Unique chunk identifier")
    query_id: int = Field(..., description="Original MS MARCO-XI query ID or 0 for web")
    language_code: str = Field(..., description="Target language script code")
    language_name: str = Field(..., description="Human-readable language name")
    source_lang: str = Field(..., description="Original source language (e.g. 'en')")
    target_lang: str = Field(..., description="Target translation language")
    similarity_score: float = Field(..., description="Cosine similarity score of chunk to query")
    text_snippet: str = Field(..., description="Truncated preview snippet of retrieved chunk text")
    title: Optional[str] = Field(default=None, description="Title of source document or web page")
    url: Optional[str] = Field(default=None, description="URL of source document or web page")
    domain: Optional[str] = Field(default=None, description="Domain name of source document or web page")


class AskResponse(BaseModel):
    """Complete answer generation response container with verification metrics and timing breakdown."""
    query: str = Field(..., description="Original user input query string preserved exactly")
    answer: str = Field(..., description="Context-grounded answer text generated by LLM or localized fallback")
    answer_language: str = Field(..., description="Language code of generated answer")
    grounding_status: GroundingStatus = Field(..., description="Grounding status flag")
    grounding_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Measured context alignment score (0.0 to 1.0)")
    sources: List[SourceAttribution] = Field(default_factory=list, description="List of validated attributed source chunks")
    source_type: str = Field(default="local_rag", description="Source provenance type: 'local_rag', 'web', or 'hybrid'")
    retrieval_latency_ms: float = Field(..., description="Measured Phase 6 local RAG or web retrieval latency in ms")
    generation_latency_ms: float = Field(..., description="Measured LLM answer generation latency in ms")
    prompt_construction_latency_ms: float = Field(default=0.0, description="Measured prompt construction latency in ms")
    llm_request_latency_ms: float = Field(default=0.0, description="Measured LLM API request/network latency in ms")
    verification_latency_ms: float = Field(default=0.0, description="Measured grounding verification engine latency in ms")
    guardrail_latency_ms: float = Field(default=0.0, description="Measured safety screening and grounding verification latency in ms")
    total_latency_ms: float = Field(..., description="Measured total end-to-end latency in ms")
    low_confidence_warning: bool = Field(default=False, description="True if top retrieval score fell below threshold or no results match")
    input_token_count: Optional[int] = Field(default=None, description="Input prompt token count if reported or estimated")
    output_token_count: Optional[int] = Field(default=None, description="Output token count if reported by provider")
    provider_used: str = Field(default="gemini", description="LLM provider actually used: 'gemini', 'groq', or 'none'")
    model_used: str = Field(default="gemini-3.6-flash", description="LLM model identifier used")
    groq_llm_latency_ms: float = Field(default=0.0, description="Measured Groq API latency in ms")
    groq_attempted: bool = Field(default=False, description="Whether Groq primary provider was attempted")
    groq_success: bool = Field(default=False, description="Whether Groq primary provider succeeded")
    groq_calls: int = Field(default=0, description="Number of Groq API calls executed for this request (0 or 1)")
    groq_error_type: Optional[str] = Field(default=None, description="Diagnostic error classification for Groq if failed")
    request_id: Optional[str] = Field(default=None, description="Unique request tracking identifier (req_<uuid>)")
