"""
Trace Web Evidence & Groq generation for 'What is the capital of Goa?'
"""

import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend")))

from app.rag.web_search import WebSearchService
from app.rag.llm.factory import get_llm_provider
from app.rag.prompts import SYSTEM_GROUNDING_PROMPT
from app.rag.guardrails.injection import InjectionDefense
from app.rag.guardrails.verifier import GroundingVerifier

def trace_web_goa():
    query = "What is the capital of Goa?"
    print("=" * 80)
    print(f"Tracing Web Evidence + Groq + Verifier for: '{query}'")
    print("=" * 80)

    web = WebSearchService()
    chunks = web.search(query, max_results=3)

    print(f"Number of Web Chunks Retrieved: {len(chunks)}")
    for i, c in enumerate(chunks):
        print(f"\nChunk #{i+1} Title: '{c.title}' | URL: '{c.url}'")
        print(f"Text Snippet:\n{c.text}")

    context_str = InjectionDefense.format_untrusted_context(chunks)
    query_str = InjectionDefense.format_untrusted_query(query)

    sys_prompt = SYSTEM_GROUNDING_PROMPT.format(
        target_language="en",
        context_blocks=context_str,
        user_query=query_str
    )

    llm = get_llm_provider()
    cand = llm.generate(
        prompt=f"Please answer the user's question based strictly on the context:\n\n{query_str}",
        system_instruction=sys_prompt
    )

    print(f"\nCandidate Answer generated by Groq: '{cand}'")

    verifier = GroundingVerifier()
    state, status, score = verifier.verify(cand, chunks)

    print(f"\nGrounding Verifier Status : {status}")
    print(f"Grounding Verifier Score  : {score:.4f}")

if __name__ == "__main__":
    trace_web_goa()
